### ISSUE TITLE
Contents Module

### ISSUE THREAD

**Issue by marvinkome** [marvinkome/contentlify#10]
- [x] CRUD for contents
- [x] Design page for creating and editing contents
- [ ] Design dialog for deleting contents
